### ISSUE TITLE
Feature request: add servericon command

### ISSUE THREAD

**Issue by PuneetGopinath** [InfusionBot/Welcome-Bot#206]
Please check these things before submitting your issue:

- [x] I searched for duplicate or closed feature request [here](https://github.com/Welcome-Bot/welcome-bot/issues?q=is%3Aissue)

**Is your feature request related to a problem? Please describe.**

N/A.

**Describe the solution you'd like**

Add a servericon command to display the guild avatar in an embed.

**Describe alternatives you've considered**

N/A.

**Additional context**

Use this for the icon URL `message.guild.iconURL({ dynamic: true, size: 512 });`

**Comment by neeraj395** [comment]
...

**Comment by neeraj395** [comment]
Please close this @PuneetGopinath
